version: '3.2'
services:
  kafka:
    image: docker.io/apache/kafka:latest
    container_name: kafka-kraft
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      # KRaft Alapbeállítások (Kombinált Node)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      # Hallgatók és Biztonsági Protokollok
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

      # Dinamikus IP meghatározás a gazdagép felé (Hasonlóan a korábbi megoldásodhoz)
      # Megjegyzés: Ha fix IP-d vagy domained van, írd be közvetlenül a localhost helyére!
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://${MY_HOST_IP}:9094

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      # Perzisztens adatok rögzítése az új belső elérési útra
      - type: bind
        source: ~/kafkadata
        target: /var/lib/kafka/data

  mongodb:
    image: mongo:latest
    deploy:
      mode: global
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ~/mongodbdata
        target: /data/db
