version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    deploy:
      mode: global
    ports:
      - "9092:9092"
      #- target: 9094
        #published: 9094
        #protocol: tcp
        #mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      #KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.0.12:9094
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "blog-command:1:1, client-commands:1:1, blog-event:1:1, performance:1:1, discussion-event:1:1, web-app:1:1, user:1:1, discussion-command:1:1, error:1:1"
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/kafkadata
        target: /kafka/kafka-logs
  mongodb:
    image: mongo:latest
    deploy:
      mode: global
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ~/mongodbdata
        target: /data/db
